### ISSUE TITLE
Изменить название маршрутов

### ISSUE THREAD

**Issue by olegpolyakov** [DonVeds/eShop#2]
Не понятно что такое `/b` и `/s`. Мне кажется маршруты можно назвать немного более понятно: `/buy` и `/sell` может быть?)

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №1](https://trello.com/c/Yt3GyAee/1-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%961)

**Comment by DonVeds** [comment]
Хорошо, сейчас исправлю, я просто брал пример с eBay
